# encoding: UTF-8

require "rubygems"
require "thor"
require "faker"
require "os"
require "yaml"
require "erb"
require "shellwords"
require "capistrano/all"

module ThemeJuice
end

require "theme-juice/version"
require "theme-juice/helpers/singleton_helper"
require "theme-juice/helpers/hash_helper"
require "theme-juice/env"
require "theme-juice/project"
require "theme-juice/util"
require "theme-juice/io"
require "theme-juice/config"
require "theme-juice/task"
require "theme-juice/tasks/entry"
require "theme-juice/tasks/create_confirm"
require "theme-juice/tasks/location"
require "theme-juice/tasks/template"
require "theme-juice/tasks/repo"
require "theme-juice/tasks/dot_env"
require "theme-juice/tasks/wp_config"
require "theme-juice/tasks/database"
require "theme-juice/tasks/create_success"
require "theme-juice/tasks/list"
require "theme-juice/tasks/stage"
require "theme-juice/tasks/valet_stage"
require "theme-juice/tasks/settings"
require "theme-juice/tasks/load"
require "theme-juice/tasks/invoke"
require "theme-juice/command"
require "theme-juice/commands/create"
require "theme-juice/commands/deploy"
require "theme-juice/cli"
